version: "3.9"
services:
  web:
    build: .
    ports:
      - "8081:8080"

  db:
    image: postgres:14.5
    restart: always
    ports:
      - "15432:5432"
    env_file:
      - ".env"
    volumes:
      - "./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
