version: "3.9"
services:
  web:
    depends_on:
      - db
#    restart: on-failure
    build:
      context: .
      args:
        - SPRING_PROFILE=dev-docker
    ports:
      - "8081:8080"

  db:
    image: postgres:14.5
    restart: always
    ports:
      - "15432:5432"
    env_file:
      - ".env"
    volumes:
      - "./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "pgdata:/var/lib/postgresql/data"

  consumer:
    depends_on:
      - rabbitmq
    build: C:\Users\mrmis\PycharmProjects\python-mq-consumer
    restart: on-failure
    env_file:
      - ".env"

  rabbitmq:
    hostname: $RABBIT_HOSTNAME
    image: rabbitmq:management
    ports:
      - "15672:15672"
    env_file:
      - ".env"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  pgdata:
