server:
  port: 8080

spring.mvc.pathmatch.matching-strategy: ant_path_matcher

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: mypass
